services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile
      args:
        - API_URL=http://127.0.0.1:8089
    ports:
      - "8087:3000"
    depends_on:
      - server
  server:
    build:
      context: ./api
      dockerfile: dockerfile      
    ports:
      - "8089:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"