version: '3.8'

services:
  # Servicio de PostgreSQL
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1489
      POSTGRES_DB: olaclickdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # Servicio de Redis
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - backend

  # Servicio de RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"  # Puerto para la interfaz de gestión de RabbitMQ
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
