export const menus = [
    { menu: 'Adobo Arequipeño', price: 64.30 },
    { menu: 'Ají de Gallina', price: 35.30 },
    { menu: 'AnƟcuchos de Corazón', price: 35.20 },
    { menu: 'Arroz Chaufa de Mariscos', price: 32.60 },
    { menu: 'Arroz con Pollo', price: 25.50 },
    { menu: 'Carapulcra con Sopa Seca', price: 35.80 },
    { menu: 'Causa Limeña', price: 30.00 },
    { menu: 'Ceviche de Pescado', price: 40.00 },
    { menu: 'Chupe de Camarones', price: 58.70 },
    { menu: 'Juane de Gallina', price: 41.60 },
    { menu: 'Lomo Saltado', price: 55.50 },
    { menu: 'Olluquito con Charqui', price: 53.30 },
    { menu: 'Pachamanca', price: 32.00 },
    { menu: 'Parihuela', price: 54.50 },
    { menu: 'Pollo a la Brasa', price: 35.20 },
    { menu: 'Pollo a la Norteña', price: 36.20 },
    { menu: 'Rocoto Relleno con Pastel de Papa', price: 37.30 },
    { menu: 'Seco de Res con Frejoles', price: 25.30 },
    { menu: 'Sudado de Pescado', price: 41.25 },
    { menu: 'Tacu Tacu con Lomo Saltado', price: 34.50 },
   ]; 
   